version: '3.2'
services:
  php-cli:
    image: korowai/php:cli
    depends_on:
      - ldap-service
    volumes:
      - .:/korowai
    working_dir: /korowai
    entrypoint: [ "dockerize", "-wait", "tcp://ldap-service:389", "-timeout", "10s" ]

  http-service:
    image: korowai/php:apache
    volumes:
      - type: bind
        source: .
        target: /korowai
      - type: volume
        source: http-logs
        target: /korowai/storage/logs

    working_dir: /korowai
    environment:
      APACHE_DOCUMENT_ROOT: "/korowai/public"

  ldap-service:
    command: [ --copy-service, --loglevel, debug]
    image: korowai/openldap
    volumes:
      - ./vendor/korowai/framework/src/Korowai/Component/Ldap/Resources/ldif/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

volumes:
  http-logs:
      driver_opts:
        type: tmpfs
        device: tmpfs
        o: "size=100m,uid=33,gid=33"
